#!/usr/bin/env python3
"""
BuggyShop Project Generator Script
Generates the complete buggy shop application structure
"""

import os
import json
from pathlib import Path

PROJECT_STRUCTURE = {
    "requirements.txt": "# ВНИМАНИЕ: специально устаревшие библиотеки для теста\nfastapi==0.95.0\nuvicorn==0.21.0\npydantic==1.10.2\nsqlalchemy==1.4.35\npython-jose==3.3.0\npasslib==1.7.4\nbcrypt==3.1.7\ncryptography==3.4.6\npython-multipart==0.0.5\npillow==8.0.0\nrequests==2.26.0\npytest==6.2.5\npytest-asyncio==0.18.0\nsqlalchemy-utils==0.37.0",
    
    "Dockerfile": "FROM python:3.9-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY . .\nENV DEBUG=True\nENV SECRET_KEY=123456\nEXPOSE 8000\nCMD [\"uvicorn\", \"src.main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\", \"--reload\"]",
    
    ".gitignore": "__pycache__/\n*.py[cod]\n*$py.class\n*.so\n.Python\nenv/\nvenv/\nENV/\nbuild/\ndevelop-eggs/\ndist/\ndownloads/\neggs/\n.eggs/\nlib/\nlib64/\nparts/\nsdist/\nvar/\nwheels/\n*.egg-info/\n.installed.cfg\n*.egg\n.pytest_cache/\n.coverage\nhtmlcov/\n.idea/\n.vscode/\n*.swp\n*.swo\n*~\n.DS_Store\nbugg_shop.db\ntest.db\nuploads/",
}

def create_project_structure():
    """Создать структуру проекта"""
    base_path = Path("buggy-shop")
    
    # Создать директории
    directories = [
        "src",
        "src/auth",
        "src/products",
        "src/orders",
        "src/uploads",
        "src/utils",
        "tests",
        ".github/workflows",
        "uploads",
    ]
    
    for dir_path in directories:
        (base_path / dir_path).mkdir(parents=True, exist_ok=True)
        init_file = base_path / dir_path / "__init__.py"
        if not init_file.exists():
            init_file.write_text('"""\nAutogenerated module\n"""\n')
    
    # Создать базовые файлы
    for file_name, content in PROJECT_STRUCTURE.items():
        file_path = base_path / file_name
        if not file_path.exists():
            file_path.write_text(content)
            print(f"✅ Created {file_name}")

def main():
    print("🚀 BuggyShop Project Generator")
    print("=" * 50)
    create_project_structure()
    print("\n✨ Project structure created!")
    print("\n📋 Next steps:")
    print("1. Copy the code blocks from BUGGY-SHOP-README.md")
    print("2. Install dependencies: pip install -r requirements.txt")
    print("3. Run: python -m uvicorn src.main:app --reload")
    print("4. Open: http://localhost:8000/docs")

if __name__ == "__main__":
    main()
